#TODO:remove remote port bind
#Volume for mariaDB
services:
  mariadb:
    image: mariadb_main
    hostname: mariadb
    container_name: mariadb_inc
    volumes:
      - mariadb_vol:/mariadb
      - ${HOME}/data/secrets/db_password.txt:/mariadb/secrets/db_password.txt
      - ${HOME}/data/secrets/db_root_password.txt:/mariadb/secrets/db_root_password.txt
    #ports:
    #  - '3306:3306'
    networks:
      - wordpress 
    build:
      dockerfile: ./requirements/mariadb/Dockerfile
    env_file: ".env"
  wordpress:
    image: wordpress_main
    container_name: wordpress_inc
    hostname: wordpress
    volumes:
      - wordpress_vol:/content
      - ${HOME}/data/secrets/wordpress_admin_password.txt:/wordpress/secrets/wordpress_admin_password.txt
      - ${HOME}/data/secrets/db_password.txt:/wordpress/secrets/db_password.txt
    ports:
      - '9000:9000'
    networks:
      - wordpress
      - nginx
    depends_on:
      - mariadb
    build:
      dockerfile: ./requirements/wordpress/Dockerfile
    env_file: ".env"

#Volume for WordPress+PHP
#volumes:
#  - type: bind
#    source: ./requirements/wordpress
#    target: /wordpress
#
#Volume for NGINX
#volumes:
#  - type: bind
#    source: ./requirements/wordpress
#    target: /www


networks:
  wordpress:
    driver: bridge
  nginx:
    driver: bridge

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/srcs/requirements/mariadb
      o: bind
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/srcs/requirements/wordpress
      o: bind
